# Generated by Django 5.1 on 2025-02-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="qantity",
            new_name="quantity",
        ),
    ]
